apiVersion: apps/v1
kind: Deployment
metadata:
  name: mails-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mails
  template:
    metadata:
      labels:
        app: mails
    spec:
      containers:
        - name: mails
          image: mayankbhadeshiya/mails
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing